#!/usr/bin/env ruby

begin
require 'lidarr'
rescue LoadError
  STDERR.puts "In development, you need to use `bundle exec bin/statowl` to run your app"
  STDERR.puts "At install-time, RubyGems will make sure lib, etc. are in the load path"
  exit 64
end

# frozen_string_literal: true

require "lidarr/cli"

Lidarr::CLI.start
