#!/usr/bin/env ruby

# frozen_string_literal: true

require "lidarr"
require "lidarr/cli"
require "thor"

shell = Thor::Shell::Color.new

begin
  Lidarr::CLI::App.start
rescue Lidarr::WellFormedHttpError => e
  shell.say_error "Something went wrong, but it may be fixable!", :red
  shell.say_error "Fortunately, this can _probably_ be fixed. Error message was as follows:"
  puts ""
  shell.say_error e.message

  exit 1
end
