name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-22.04]
        ruby: [ '3.1' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Run the default task
      run: bundle exec rake test
